[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "9"
  SECRETS_SCAN_ENABLED = "false"

# Disable secrets scanning entirely since we've removed actual secret values
[build.processing.secrets]
  enabled = false